### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by Stonedestroyer** [fethica/jikan-rest-docker#1]
Hey, when browsing to http://ip:9000 with ip being my IP I get 

```
Forbidden
You don't have permission to access / on this server.
```
And it seems logs show me 

AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive

And trying to go on http://ip:9000/public/v3
gives me 
```
<br />
<b>Fatal error</b>:  Uncaught UnexpectedValueException: The stream or file &quot;/var/www/html/storage/logs/lumen.log&quot; could not be opened: failed to open stream: Permission denied in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler-&gt;write(Array)
#1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler-&gt;handle(Array)
#2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\Logger-&gt;addRecord(400, Object(UnexpectedValueException), Array)
#3 /var/www/html/vendor/laravel/lumen-framework/src/Exceptions/Handler.php(45): Monolog\Logger-&gt;error(Object(UnexpectedValueException))
#4 /var/www/html/app/Exceptions/Handler.php(46): Laravel\Lumen\Exceptions\Handler-&gt;report(Object(UnexpectedValueException))
#5 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(122): App\Except in <b>/var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php</b> on line <b>107</b><br />
<br />
<b>Fatal error</b>:  Uncaught UnexpectedValueException: The stream or file &quot;/var/www/html/storage/logs/lumen.log&quot; could not be opened: failed to open stream: Permission denied in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler-&gt;write(Array)
#1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler-&gt;handle(Array)
#2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\Logger-&gt;addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 /var/www/html/vendor/laravel/lumen-framework/src/Exceptions/Handler.php(45): Monolog\Logger-&gt;error(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /var/www/html/app/Exceptions/Handler.php(46): Laravel\Lumen\Exceptions\Handler-&gt;report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#5 /var/www/html/vend in <b>/var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php</b> on line <b>107</b><br />
```

**Comment by tzw0745** [comment]
i got the same issue.
php don't have enough permission to write file in `/var/www/html/storage/`. you can do follow command to fix this:
```shell
docker exec -it $(docker ps | grep 9000 | awk '{print $1}') bash
chmod -R 777 storage/
exit
```

**Comment by fethica** [comment]
This issue has been fixed with @tzw0745 's PR: https://github.com/fethica/jikan-rest-docker/pull/4
